[extend]
useDefault = true

[[allowlists]]
description = "Anthropic CLI OAuth public client identifier"
regexTarget = "match"
regexes = ['''ANTHROPIC_OAUTH_CLIENT_ID", "9d1c250a-e61b-44d9-88ed-5944d1962f5e''']
